.TH FIX-DIGITS 1 2023 FIX-DIGITS\ 0.1.2

.SH NAME
fix-digits \- add leading zeros to numbers in filenames

.SH SYNOPSIS
.SY
\fBfix-digits\fR [<options>] [<file> ...]
.YS

.SH DESCRIPTION
\fBfix-digits\fR allows the user to bulk-rename files by zero-padding numbers in filenames such that all numbers in those filenames have an equal number of digits. 

For example:

.RS
.TS
l c l .
1-name.ext	->	001-name.ext
2-name.ext	->	002-name.ext
3-name.ext	->	003-name.ext
4-name.ext	->	004-name.ext
5-name.ext	->	005-name.ext
6-name.ext	->	006-name.ext
7-name.ext	->	007-name.ext
8-name.ext	->	008-name.ext
9-name.ext	->	009-name.ext
10-name.ext	->	010-name.ext
11-name.ext	->	011-name.ext
12-name.ext	->	012-name.ext
\...
99-name.ext	->	099-name.ext
100-name.ext	->	100-name.ext
.TE
.RE

This ensures that the files are always sorted in the intended numerical order \- whether or not a given program supports a sorting method that would allow for such a sort order without the numbers in filenames having leading zeros added.

Renaming is done by matching parts of the filenames that immediately precede and follow the numeric part, with regular expressions. This allows \fBfix-digits\fR to identify the part that contains the numbers, and rename the files. These regular expressions are set by using the \fB-b, --before\fR and \fB-a, --after\fR options.

By default, \fBfix-digits\fR does not rename the files, but only simulates the renaming, providing the user with a preview of the changes to be made. The actual renaming can then be done by running `fix-digits -r [<file> ...]`.

If no <file> argument is passed to \fBfix-digits\fR, it performs the operation on all files in the current working directory (except for the files whose names start with a dot). This is equivalent to running `fix-digits [<options>] *` (with `shopt dotglob` set to `off`).

If a file with the same name already exists, it will not be renamed, a warning message will appear, and \fBfix-digits\fR will exit with exit code \fB2\fR.

.SH OPTIONS

.TP
.B -b, --before\fR=<regex>
Regular expression to match the part of the filenames immediately preceding the numbers. Note that matching is performed only on the basename of the file (i.e. not on the path that might precede the filename).

The default value is `^`.

Also see REGULAR EXPESSIONS below.

.TP
.B -a, --after\fR=<regex>
Regular expression to match the part of the filenames immediately following the numbers.

The default value is `-.*$`.

Also see REGULAR EXPESSIONS below.

.TP
.B -r, --rename
Rename the files instead of simulating the renaming.

.TP
.B -R, --no-rename
Do not rename the files, only simulate the renaming. This is the default.

.TP
.B -c, --color
Colorize the output. This is the default.

.TP
.B -C, --no-color
Disable colorization of the output.

.TP
.B -h, --help
Print help.

.TP
.B -V, --version
Print version information.

.SH REGULAR EXPRESSIONS

The regular expressions used are POSIX Extended Regular Expressions as used in Bash, in the `[[ <value> =~ <regex> ]]` construct. More information on POSIX Regular Expressions can be found at <https://www.gnu.org/software/grep/manual/html_node/Regular-Expressions.html>.

.SH FILES

A configuration file can be used to set default options.

The configuration file's location is \fI$XDG_CONFIG_HOME/fix-digits/config.bash\fR. If \fIXDG_CONFIG_HOME\fR is not set, it defaults to \fI~/.config\fR.

.SH EXIT CODES

\fBfix-digits\fR returns the following exit codes:

.TS
l l .
\fB0\fR	Success. No errors have occured.
\fB1\fR	A general error has occured.
\fB2\fR	Renaming failed. File with the same name already exists. See output for more details.
.TE

.SH AUTHOR

Alex Rogers <https://github.com/linguisticmind>

.SH HOMEPAGE

<https://github.com/linguisticmind/fix-digits>

.SH COPYRIGHT

Copyright © 2023 Alex Rogers. License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.

This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
